import React, { useEffect, useState } from 'react';
import { Bot, Check, ChevronRight, LoaderCircle, MemoryStick, Plus, Save, Sparkles, Trash2, Workflow } from 'lucide-react';
import './WorkspaceModules.css';
import { jsonOptions, ModuleWelcome, request } from './WorkspaceModuleShared.jsx';

export function CopilotModule({ skills = [], onToast }) {
  const [copilots, setCopilots] = useState([]);
  const [activeId, setActiveId] = useState(null);
  const [selectedId, setSelectedId] = useState(null);
  const [form, setForm] = useState(null);
  const [busy, setBusy] = useState('loading');
  async function load(preferred) { setBusy('loading'); try { const data = await request('/api/copilots'); setCopilots(data.copilots); setActiveId(data.activeCopilotId); const next = data.copilots.find(item => item.id === (preferred || selectedId)) || data.copilots[0] || null; setSelectedId(next?.id || null); setForm(next ? { ...next, userPrompt: next.userPrompt ?? next.systemPrompt ?? '', memoriesText: (next.memories || []).join('\n') } : null); } catch (error) { onToast?.(error.message, 'error'); } finally { setBusy(''); } }
  useEffect(() => { load(); }, []);
  function select(item) { setSelectedId(item.id); setForm({ ...item, userPrompt: item.userPrompt ?? item.systemPrompt ?? '', memoriesText: (item.memories || []).join('\n') }); }
  async function createCopilot() { setBusy('create'); try { const data = await request('/api/copilots', jsonOptions('POST', { name: '新 Copilot', avatar: '🤖', userPrompt: '基于已连接知识提供准确、可追溯、可执行的回答。', skillIds: [], activate: true })); await load(data.copilot.id); onToast?.('已创建并激活 Copilot'); } catch (error) { onToast?.(error.message, 'error'); } finally { setBusy(''); } }
  async function save(activate = false) { if (!form?.id) return; setBusy('save'); try { const memories = String(form.memoriesText || '').split(/\n+/).map(item => item.trim()).filter(Boolean); const data = await request(`/api/copilots/${form.id}`, jsonOptions('PATCH', { name: form.name, avatar: form.avatar, userPrompt: form.userPrompt, skillIds: form.skillIds || [], memoryEnabled: form.memoryEnabled !== false, memories, activate })); setForm({ ...data.copilot, userPrompt: data.copilot.userPrompt ?? data.copilot.systemPrompt ?? '', memoriesText: memories.join('\n') }); setCopilots(current => current.map(item => item.id === data.copilot.id ? data.copilot : item)); if (activate) setActiveId(data.copilot.id); onToast?.(activate ? 'Copilot 已保存并激活' : 'Copilot 已保存'); } catch (error) { onToast?.(error.message, 'error'); } finally { setBusy(''); } }
  async function remove() { if (!form?.id) return; try { await request(`/api/copilots/${form.id}`, { method: 'DELETE' }); await load(); onToast?.('Copilot 已删除'); } catch (error) { onToast?.(error.message, 'error'); } }
  function toggleSkill(id) { setForm(current => ({ ...current, skillIds: (current.skillIds || []).includes(id) ? current.skillIds.filter(item => item !== id) : [...(current.skillIds || []), id] })); }
  return <>
    <aside className="side-panel module-side"><div className="side-head"><div><span>Personal Agents</span><h2>我的 Copilot</h2></div><button onClick={createCopilot}><Plus size={17}/></button></div><div className="module-list padded">{busy === 'loading' ? <div className="module-empty"><LoaderCircle className="spin"/>读取 Copilot…</div> : copilots.map(item => <button key={item.id} className={selectedId === item.id ? 'active' : ''} onClick={() => select(item)}><span className="copilot-avatar">{item.avatar || '🤖'}</span><span><b>{item.name}</b><small>{item.id === activeId ? '当前激活' : `${item.skillIds?.length || 0} 个 Skill`}</small></span>{item.id === activeId ? <Check size={14}/> : <ChevronRight size={14}/>}</button>)}</div></aside>
    <main className="workspace module-workspace">{form ? <><header className="workspace-head"><div className="workspace-title"><span className="ai-avatar"><Bot size={19}/></span><div><strong>Copilot 配置</strong><small>{form.id === activeId ? '当前会话默认使用' : '独立提示词、Skill 和长期偏好'}</small></div></div><div className="head-actions"><button onClick={() => save(false)}><Save size={16}/>保存</button><button className="primary-inline" onClick={() => save(true)}><Sparkles size={16}/>保存并激活</button><button className="danger-lite" onClick={remove}><Trash2 size={16}/></button></div></header><div className="copilot-canvas"><section className="copilot-form"><div className="avatar-name"><input value={form.avatar || ''} onChange={event => setForm(current => ({ ...current, avatar: event.target.value }))}/><input value={form.name || ''} onChange={event => setForm(current => ({ ...current, name: event.target.value }))}/></div><label><span>用户自定义指令</span><textarea className="user-prompt-input" value={form.userPrompt || ''} onChange={event => setForm(current => ({ ...current, userPrompt: event.target.value }))} placeholder="告诉这个 Copilot 你的工作偏好、输出方式和需要关注的重点…"/><small className="prompt-hint">系统级规则由 FlowMind 内置维护；这里仅填写你自己的工作要求。</small></label><label><span>长期偏好与记忆</span><textarea className="memory-input" value={form.memoriesText || ''} onChange={event => setForm(current => ({ ...current, memoriesText: event.target.value }))} placeholder={'每行一条，例如：\n优先输出表格\n所有结论带引用'}/></label><label className="memory-switch"><MemoryStick size={17}/><span><b>启用记忆</b><small>在后续会话中使用已保存偏好</small></span><input type="checkbox" checked={form.memoryEnabled !== false} onChange={event => setForm(current => ({ ...current, memoryEnabled: event.target.checked }))}/></label></section><aside className="copilot-skills"><h3><Workflow size={17}/>绑定 Skills</h3><p>只为这个 Copilot 启用需要的工作流。</p>{skills.map(skill => <button key={skill.id} className={(form.skillIds || []).includes(skill.id) ? 'selected' : ''} onClick={() => toggleSkill(skill.id)}><span><b>{skill.name}</b><small>{skill.description}</small></span>{(form.skillIds || []).includes(skill.id) && <Check size={15}/>}</button>)}</aside></div></> : <ModuleWelcome icon={Bot} title="创建你的专属 Copilot" description="为不同工作场景配置独立角色、知识范围、Skill 和长期偏好。" action={createCopilot} actionLabel="创建 Copilot"/>}</main>
  </>;
}
