import React, { useEffect, useRef, useState } from 'react';
import { ArchiveRestore, ChevronRight, Clock3, FilePenLine, Link2, LoaderCircle, Plus, Save } from 'lucide-react';
import './WorkspaceModules.css';
import { formatTime, jsonOptions, ModuleWelcome, request } from './WorkspaceModuleShared.jsx';

export function WritingModule({ onToast, initialDraftId = '', onOpenDocument }) {
  const [drafts, setDrafts] = useState([]);
  const [selectedId, setSelectedId] = useState(null);
  const [draft, setDraft] = useState(null);
  const [busy, setBusy] = useState('loading');
  const [dirty, setDirty] = useState(false);
  const timer = useRef(null);
  async function load() { try { const data = await request('/api/writing/drafts'); setDrafts(data.drafts); const next = data.drafts.find(item => item.id === initialDraftId) || data.drafts.find(item => item.id === selectedId) || data.drafts[0] || null; setSelectedId(next?.id || null); setDraft(next); } catch (error) { onToast?.(error.message, 'error'); } finally { setBusy(''); } }
  useEffect(() => { load(); return () => clearTimeout(timer.current); }, [initialDraftId]);
  useEffect(() => { if (!dirty || !draft?.id) return; clearTimeout(timer.current); timer.current = setTimeout(() => save(true), 800); return () => clearTimeout(timer.current); }, [draft?.title, draft?.content, draft?.template, draft?.audience, draft?.tone, dirty]);
  function select(item) { clearTimeout(timer.current); setSelectedId(item.id); setDraft(item); setDirty(false); }
  function update(patch) { setDraft(current => ({ ...current, ...patch })); setDirty(true); }
  async function createDraft() { setBusy('create'); try { const data = await request('/api/writing/drafts', jsonOptions('POST', { title: '新写作草稿', content: '', template: 'freeform', audience: '', tone: '专业' })); setDrafts(current => [data.draft, ...current]); select(data.draft); onToast?.('已创建写作草稿'); } catch (error) { onToast?.(error.message, 'error'); } finally { setBusy(''); } }
  async function save(silent = false) { if (!draft?.id || !dirty) return; setBusy('save'); try { const data = await request(`/api/writing/drafts/${draft.id}`, jsonOptions('PATCH', { title: draft.title, content: draft.content, template: draft.template, audience: draft.audience, tone: draft.tone })); setDraft(data.draft); setDrafts(current => current.map(item => item.id === data.draft.id ? data.draft : item)); setDirty(false); if (!silent) onToast?.('草稿已保存并生成版本'); } catch (error) { onToast?.(error.message, 'error'); } finally { setBusy(''); } }
  function restore(version) { update({ content: version.content }); onToast?.('历史版本已载入编辑器'); }
  const sourceRefs = Array.isArray(draft?.sourceRefs) ? draft.sourceRefs : [];
  return <>
    <aside className="side-panel module-side"><div className="side-head"><div><span>AI Writing</span><h2>智能写作</h2></div><button onClick={createDraft}><Plus size={17}/></button></div><div className="module-list padded">{busy === 'loading' ? <div className="module-empty"><LoaderCircle className="spin"/>读取草稿…</div> : drafts.length ? drafts.map(item => <button key={item.id} className={selectedId === item.id ? 'active' : ''} onClick={() => select(item)}><FilePenLine size={16}/><span><b>{item.title}</b><small>{item.template} · {formatTime(item.updatedAt)}</small></span><ChevronRight size={14}/></button>) : <div className="module-empty"><FilePenLine size={25}/><b>暂无草稿</b><small>从空白页开始写作</small></div>}</div></aside>
    <main className="workspace module-workspace">{draft ? <><header className="workspace-head"><div className="workspace-title"><span className="ai-avatar"><FilePenLine size={19}/></span><div><strong>智能写作</strong><small>{dirty ? '编辑中 · 将自动保存' : `${draft.versions?.length || 0} 个历史版本`}</small></div></div><div className="head-actions"><button onClick={() => save(false)} disabled={!dirty || busy === 'save'}>{busy === 'save' ? <LoaderCircle className="spin" size={16}/> : <Save size={16}/>}保存版本</button></div></header><div className="writing-layout"><section className="editor-canvas"><input className="editor-title" value={draft.title} onChange={event => update({ title: event.target.value })}/><div className="writing-meta"><label>模板<select value={draft.template || 'freeform'} onChange={event => update({ template: event.target.value })}><option value="freeform">自由写作</option><option value="weekly">周报</option><option value="proposal">方案</option><option value="article">文章</option><option value="brief">简报</option></select></label><label>受众<input value={draft.audience || ''} onChange={event => update({ audience: event.target.value })} placeholder="团队 / 客户 / 管理层"/></label><label>语气<input value={draft.tone || ''} onChange={event => update({ tone: event.target.value })} placeholder="专业、简洁"/></label></div><textarea className="editor-body" value={draft.content || ''} onChange={event => update({ content: event.target.value })} placeholder="在这里开始写作。后续可直接调用知识库证据与 Skill 生成内容。"/></section><aside className="version-panel"><section className="writing-sources"><h3><Link2 size={16}/>{'\u6765\u6e90\u6750\u6599'} <span>{sourceRefs.length}</span></h3>{sourceRefs.length ? sourceRefs.map((ref, index) => <button type="button" key={`${ref.documentId || ref.sourceId || ref.url || ref.title || index}:${index}`} disabled={!ref.documentId || typeof onOpenDocument !== 'function'} onClick={() => onOpenDocument?.({ ...ref, id: ref.documentId, documentId: ref.documentId, title: ref.title || '\u6765\u6e90\u6587\u6863', source: ref.source || ref.kind })}><span><b>{ref.title || '\u6765\u6e90\u6750\u6599'}</b><small>{ref.quote || ref.source || ref.kind || ref.type || '\u5199\u4f5c\u6765\u6e90'}</small></span><ChevronRight size={14}/></button>) : <p>{'\u6b64\u8349\u7a3f\u6682\u672a\u9644\u52a0\u6765\u6e90\u3002'}</p>}</section><h3><Clock3 size={16}/>版本历史</h3>{draft.versions?.length ? [...draft.versions].reverse().map((version, index) => <button key={`${version.savedAt}-${index}`} onClick={() => restore(version)}><span><b>{formatTime(version.savedAt)}</b><small>{String(version.content || '').slice(0, 70) || '空白版本'}</small></span><ArchiveRestore size={14}/></button>) : <div className="module-empty"><Clock3 size={22}/><small>内容变化后会保留版本</small></div>}</aside></div></> : <ModuleWelcome icon={FilePenLine} title="把知识变成可交付内容" description="创建草稿、配置模板/受众/语气，并保留可恢复的版本历史。" action={createDraft} actionLabel="创建写作草稿"/>}</main>
  </>;
}
